language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '10.14'
before_script:
- npm prune
- npm install
script:
- npm run build && npm run test:prod
after_success:
- 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
- "./scripts/upload-coverage.sh"
- "./scripts/npm-publish.js"
- "./scripts/gh-pages-publish.js"
