language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '8.9'
before_script:
- npm prune
- npm install
script:
- npm run build && npm run test:prod
after_success:
- openssl aes-256-cbc -K $encrypted_a6513114b0a4_key -iv $encrypted_a6513114b0a4_iv
  -in common/npmrc.enc -out ~/.npmrc -d
- "./scripts/upload-coverage.sh"
- "./scripts/npm-publish.js"
- "./scripts/gh-pages-publish.js"
